openapi: 3.0.0
info:
  title: CineVerse API
  version: 1.0.0
servers:
  - url: "https://honey-inoxidizable-topically.ngrok-free.dev"
    description: Local dev server
paths:
  /api/bookings/seats/status/:
    get:
      tags:
        - bookings
      summary: Get seat status for a show
      parameters:
        - name: show_id
          in: query
          required: true
          schema:
            type: integer
          description: ID of the show
      responses:
        '200':
          description: List of seats status
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    seat_id:
                      type: integer
                    locked_seat_id:
                      oneOf:
                        - type: integer
                        - nullable: true
                    status:
                      type: string
                    rownumber:
                      type: integer
                    colomnnumber:
                      type: integer
                    seattype:
                      type: string
                    price:
                      type: number
        '400':
          description: Bad request - missing show_id
        '404':
          description: Show not found

  /api/bookings/seats/lock/:
    post:
      tags:
        - bookings
      summary: Lock multiple seats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - show_id
                - locked_seat_ids
              properties:
                show_id:
                  type: integer
                locked_seat_ids:
                  type: array
                  items:
                    type: integer
            example:
              show_id: 1
              locked_seat_ids: [10, 14, 15]
      responses:
        '200':
          description: Lock results for each seat
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        locked_seat_id:
                          type: integer
                        result:
                          type: string
        '400':
          description: Bad request - missing parameters

  /api/bookings/seats/book/:
    post:
      tags:
        - bookings
      summary: Mark seats as booked
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - show_id
                - locked_seat_ids
              properties:
                show_id:
                  type: integer
                locked_seat_ids:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Book status for each seat
          content:
            application/json:
              schema:
                type: object
                properties:
                  booked:
                    type: array
                    items:
                      type: integer
                  notfound:
                    type: array
                    items:
                      type: integer
        '400':
          description: Bad request - missing parameters

  /api/bookings/seats/create-booking/:
    post:
      tags:
        - bookings
      summary: Create a new booking
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - locked_seat_ids
                - totalamount
                - show_id
                - payment_id
              properties:
                user_id:
                  type: integer
                locked_seat_ids:
                  type: array
                  items:
                    type: integer
                totalamount:
                  type: number
                  format: float
                show_id:
                  type: integer
                payment_id:
                  type: string
      responses:
        '200':
          description: Booking creation success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  booking_id:
                    type: integer
        '400':
          description: Bad request - missing parameters or some seats not found
        '404':
          description: User or show not found

  /api/bookings/seats/your-orders/:
    get:
      tags:
        - bookings
      summary: Get all bookings for a user
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
          description: ID of the user
      responses:
        '200':
          description: List of bookings for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '400':
          description: Bad request - missing user_id
        '404':
          description: User not found

  /api/movies/search/:
    get:
      tags:
        - movies
      summary: Search movies by title prefix
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
          description: Query string to match start of movie title
      responses:
        '200':
          description: List of matching movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieSearch'

  /api/movies/details/:
    get:
      tags:
        - movies
      summary: Get detailed info of a movie by ID
      parameters:
        - name: movie_id
          in: query
          required: true
          schema:
            type: integer
          description: ID of the movie
      responses:
        '200':
          description: Movie details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieDetails'
        '404':
          description: Movie not found

  /api/shows/movies-by-location/:
    get:
      tags:
        - shows
      summary: Get movies playing at a location
      parameters:
        - name: location_id
          in: query
          required: false
          schema:
            type: integer
          description: Optional location ID to filter movies
      responses:
        '200':
          description: List of movies with id, title, and poster
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    movie_id:
                      type: integer
                    title:
                      type: string
                    poster:
                      type: string
                      format: uri

  /api/shows/shows-by-movie/:
    get:
      tags:
        - shows
      summary: Get shows for a movie at a location
      parameters:
        - name: movie_id
          in: query
          required: true
          schema:
            type: integer
          description: Movie ID to filter shows
        - name: location_id
          in: query
          required: true
          schema:
            type: integer
          description: Location ID to filter shows
      responses:
        '200':
          description: List of shows with detailed info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Show'
        '400':
          description: movie_id or location_id parameter is missing

  /api/theaters/locations/search/:
    get:
      tags:
        - theaters
      summary: Search locations by prefix query
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
          description: Query string to filter location names that start with this value
      responses:
        '200':
          description: List of matching locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
  /api/users/profile_details/:
    get:
      tags:
        - users
      summary: Get user profile details by user_id
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
          description: ID of the user
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Missing user_id parameter
        '404':
          description: User not found

  /api/users/edit_profile/:
    post:
      tags:
        - users
      summary: Edit user profile fields
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEdit'
      responses:
        '200':
          description: Edit success/failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  errors:
                    type: object
                    nullable: true
        '400':
          description: Bad request / validation errors
        '404':
          description: User not found

  /api/users/signup/:
    post:
      tags:
        - users
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignup'
      responses:
        '200':
          description: Signup success/failure with new user_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user_id:
                    type: integer
                  errors:
                    type: object
                    nullable: true
        '400':
          description: Validation errors

  /api/users/login/:
    post:
      tags:
        - users
      summary: Authenticate user and return profile details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login success - returns user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginSuccess'
        '400':
          description: Login failed - invalid credentials


    
components:
  securitySchemes: 
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: integer
        user:
          type: integer
        show:
          type: integer
        totalamount:
          type: number
          format: float
        bookingtime:
          type: string
          format: date-time
        payment_id:
          type: string
        seats:
          type: array
          items:
            type: integer

    MovieSearch:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        genre:
          type: string
        language:
          type: string

    MovieDetails:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        genre:
          type: string
        language:
          type: string
        duration:
          type: string
        releasedate:
          type: string
        cast:
          type: string
        poster:
          type: string

    Show:
      type: object
      properties:
        id:
          type: integer
        movie:
          type: integer
        screen:
          type: integer
        showtime:
          type: string
          format: date-time
        date:
          type: string
          format: date
        location:
          type: integer
        theater:
          type: object
          description: Theatre details from related Screen

    Location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Theater:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        totalscreens:
          type: integer
        address:
          type: string
        location:
          $ref: '#/components/schemas/Location'

    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
        gender:
          type: string
          nullable: true
        profile_image:
          type: string
          nullable: true

    UserEdit:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
          nullable: true
        email:
          type: string
          format: email
          nullable: true
        gender:
          type: string
          nullable: true

    UserSignup:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
        email:
          type: string
          format: email
        first_name:
          type: string
          nullable: true
        last_name:
          type: string
          nullable: true
        gender:
          type: string
          nullable: true

    UserLoginSuccess:
      type: object
      properties:
        success:
          type: boolean
        user_id:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        gender:
          type: string
          nullable: true