# Generated by Django 5.2.7 on 2025-10-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locked_Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('locked', 'Locked')], default='available', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookingtime', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=100)),
                ('seats', models.ManyToManyField(related_name='bookings', to='theaters.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shows.show')),
            ],
        ),
    ]
